version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./BancoSemDados.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - simulado_network

  api:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${VITE_API_PORT:-3000}:3000"
    depends_on:
      - db
    networks:
      - simulado_network

volumes:
  postgres_data:

networks:
  simulado_network:
    driver: bridge